Repository sos-sejong-opensource-software/seggle-frontend, pull requests merged in 2023-02, with the labels that each got.

#28 feat: admin 사이드바
  src/App.tsx
  src/constants/paths.ts
  src/pages/Admin/Admin.tsx
  src/pages/Admin/index.ts
  src/pages/index.ts
  webpack/webpack.common.js
Labels: 🐛bug, ✨feature

#32 feat: 수업 리스트 조회 페이지
  src/App.tsx
  src/constants/paths.ts
  src/pages/Class/ClassList.tsx
  src/pages/Class/api/index.ts
  src/pages/Class/hooks/index.ts
  src/pages/Class/hooks/query/index.ts
  src/pages/Class/hooks/query/useClassListQuery.ts
  src/pages/Class/hooks/useClassListTable.ts
  src/pages/Class/index.ts
  src/pages/index.ts
  src/types/class.d.ts
Labels: ✨feature

#24 feat: PageTitle 컴포넌트
  package-lock.json
  package.json
  postcss.config.cjs
  src/pages/Faq/Faq.tsx
  src/style/common.css
  src/style/index.css
Labels: ✨feature

#35 [feat] 토글 스위치 atom & 테이블 onRowClick 선택으로 수정
  src/components/atom/Switch.tsx
  src/components/molecule/Table.tsx
  src/pages/Home.tsx
Labels: ✨feature

#33 feat: 수업 목록 편집 페이지 - 수업 공개 여부
  src/components/atom/Input.tsx
  src/components/atom/Select.tsx
  src/pages/Class/ClassListEdit.tsx
  src/pages/Class/api/index.ts
  src/pages/Class/hooks/query/index.ts
  src/pages/Class/hooks/query/useEditClassListMutation.ts
  src/pages/Class/hooks/useClassListEditTable.tsx
  src/pages/Class/index.ts
  src/types/class.d.ts
Labels: ✨feature, ♻️refactor

#36 feat: 수업 목록 편집 페이지 - 수업 편집, 삭제
  src/constants/queryKeys.ts
  src/pages/Class/ClassListEdit.tsx
  src/pages/Class/api/index.ts
  src/pages/Class/components/ClassEditModal.tsx
  src/pages/Class/components/index.ts
  src/pages/Class/hooks/index.ts
  src/pages/Class/hooks/query/index.ts
  src/pages/Class/hooks/query/useClassQuery.ts
  src/pages/Class/hooks/query/useDeleteClassMutation.ts
  src/pages/Class/hooks/query/useEditClassMutation.ts
  src/pages/Class/hooks/useClassListEditTable.tsx
  src/pages/Class/hooks/useClassListTable.ts
  src/pages/Class/hooks/useModalBody.tsx
  src/types/class.d.ts
Labels: ✨feature

#41 feat: 수업 페이지 - 전체 문제 목록
  src/App.tsx
  src/components/atom/index.ts
  src/constants/paths.ts
  src/constants/queryKeys.ts
  src/hooks/useQueryDebounce.ts
  src/hooks/useSearch.ts
  src/pages/Class/Class.tsx
  src/pages/Class/ClassProblemList.tsx
  src/pages/Class/api/index.ts
  src/pages/Class/hooks/index.ts
  src/pages/Class/hooks/query/useProblemListQuery.ts
  src/pages/Class/hooks/useClassProblemListTable.tsx
  src/pages/Class/index.ts
  src/types/class.d.ts
  src/types/response.d.ts
Labels: ✨feature

#40 feat: 관리자 페이지 - 전체 문제 목록
  src/App.tsx
  src/constants/paths.ts
  src/constants/queryKeys.ts
  src/pages/Admin/AdminAllProblems.tsx
  src/pages/Admin/api/index.ts
  src/pages/Admin/hooks/query/useAdminAllProblemsQuery.ts
  src/pages/Admin/hooks/query/useDeleteProblemMutation.ts
  src/pages/Admin/hooks/useAdminAllProblemsTable.tsx
  src/pages/Admin/index.ts
  src/types/admin.d.ts
Labels: ✨feature

#48 [feat] 관리자페이지 - 전체문제목록 검색
  src/pages/Admin/AdminAllProblems.tsx
  src/pages/Class/hooks/query/index.ts
  src/pages/User/api/index.ts
Labels: ✨feature

#45 [feat] 비밀번호 변경
  src/App.tsx
  src/constants/paths.ts
  src/pages/User/Login.tsx
  src/pages/User/Register.tsx
  src/pages/User/ResetPassword.tsx
  src/pages/User/api/index.ts
  src/pages/User/components/ResetPasswordForm.tsx
  src/pages/User/constants/errorMessage.ts
  src/pages/User/constants/input.ts
  src/pages/User/hooks/index.ts
  src/pages/User/hooks/query/index.ts
  src/pages/User/hooks/query/useLoginMutation.ts
  src/pages/User/hooks/query/useRegisterMutation.ts
  src/pages/User/hooks/query/useResetPasswordMutation.ts
  src/pages/User/hooks/useResetPasswordForm.ts
  src/types/user.d.ts
Labels: ✨feature, ♻️refactor

#43 feat: 수업 페이지 - 수강생 및 TA 관리
  src/App.tsx
  src/constants/queryKeys.ts
  src/pages/Class/ClassStudentManagement.tsx
  src/pages/Class/api/index.ts
  src/pages/Class/components/ClassStudentForm.tsx
  src/pages/Class/components/index.ts
  src/pages/Class/hooks/index.ts
  src/pages/Class/hooks/query/index.ts
  src/pages/Class/hooks/query/useClassStudentListMutation.ts
  src/pages/Class/hooks/query/useClassStudentListQuery.ts
  src/pages/Class/hooks/query/useClassTaListMutation.ts
  src/pages/Class/hooks/query/useClassTaListQuery.ts
  src/pages/Class/hooks/useStudentForm.ts
  src/pages/Class/index.ts
  src/types/class.d.ts
Labels: ✨feature

#52 [feat] 관리자페이지 - 공지사항 목록
  src/App.tsx
  src/constants/paths.ts
  src/constants/queryKeys.ts
  src/pages/Admin/AdminAnnouncementList.tsx
  src/pages/Admin/api/index.ts
  src/pages/Admin/hooks/index.ts
  src/pages/Admin/hooks/query/index.ts
  src/pages/Admin/hooks/query/useAdminAnnouncementListQuery.ts
  src/pages/Admin/hooks/query/useDeleteAnnouncementMutation.ts
  src/pages/Admin/hooks/query/useEditAnnouncementSwitchMutation.ts
  src/pages/Admin/hooks/useAdminAnnouncementsTable.tsx
  src/pages/Admin/index.ts
  src/types/admin.d.ts
Labels: ✨feature

#51 feat: 수업 페이지 - 과제 및 시험
  src/App.tsx
  src/constants/paths.ts
  src/constants/queryKeys.ts
  src/pages/Class/Class.tsx
  src/pages/Class/ClassContest.tsx
  src/pages/Class/ClassContestProblemList.tsx
  src/pages/Class/ClassStudentManagement.tsx
  src/pages/Class/api/index.ts
  src/pages/Class/hooks/index.ts
  src/pages/Class/hooks/query/index.ts
  src/pages/Class/hooks/query/useClassContestListQuery.ts
  src/pages/Class/hooks/query/useClassContestProblemQuery.ts
  src/pages/Class/hooks/useContestProblemListTable.tsx
  src/pages/Class/index.ts
  src/types/class.d.ts
Labels: ✨feature, ♻️refactor

#54 feat: 수업 - 전체 문제 상세 조회, 문제 생성폼
  src/App.tsx
  src/constants/index.ts
  src/constants/metrics.ts
  src/constants/paths.ts
  src/pages/Class/Problem/AllProblemDetail.tsx
  src/pages/Class/Problem/ProblemData.tsx
  src/pages/Class/Problem/ProblemDescription.tsx
  src/pages/Class/Problem/ProblemForm.tsx
  src/pages/Class/Problem/ProblemLeaderBoard.tsx
  src/pages/Class/Problem/ProblemSubmission.tsx
  src/pages/Class/Problem/api/index.ts
  src/pages/Class/Problem/components/Problem.tsx
  src/pages/Class/Problem/components/index.ts
  src/pages/Class/Problem/hooks/index.ts
  src/pages/Class/Problem/hooks/query/index.ts
  src/pages/Class/Problem/hooks/query/useCreateProblemMutation.ts
  src/pages/Class/Problem/hooks/query/useProblemQuery.ts
  src/pages/Class/Problem/index.ts
  src/pages/Class/index.ts
  src/types/problem.d.ts
Labels: ✨feature

#56 feat: 수업페이지 - 전체 문제 목록 편집 / 삭제
  src/pages/Class/api/index.ts
  src/pages/Class/hooks/query/index.ts
  src/pages/Class/hooks/query/useDeleteProblemMutation.ts
  src/pages/Class/hooks/query/useEditProblemPublicMutation.ts
  src/pages/Class/hooks/useClassProblemListTable.tsx
Labels: ✨feature

#59 feat: 관리자페이지 - 공지사항 생성, 수정
  package-lock.json
  package.json
  src/App.tsx
  src/components/atom/Editor.css
  src/components/atom/Editor.tsx
  src/components/atom/Switch.tsx
  src/components/molecule/Table.tsx
  src/constants/paths.ts
  src/constants/queryKeys.ts
  src/pages/Admin/AdminAnnouncementList.tsx
  src/pages/Admin/AdminEditAnnouncement.tsx
  src/pages/Admin/AdminNewAnnouncement.tsx
  src/pages/Admin/api/index.ts
  src/pages/Admin/components/AdminCreateEditForm.tsx
  src/pages/Admin/components/index.ts
  src/pages/Admin/constants/index.ts
  src/pages/Admin/constants/label.ts
  src/pages/Admin/hooks/query/index.ts
  src/pages/Admin/hooks/query/useAdminAnnouncementQuery.ts
  src/pages/Admin/hooks/query/useCreateAnnouncementMutation.ts
  src/pages/Admin/hooks/query/useEditAnnouncementMutation.ts
  src/pages/Admin/hooks/useAdminAnnouncementsTable.tsx
  src/pages/Admin/index.ts
  src/types/admin.d.ts
Labels: ✨feature, ♻️refactor

#58 feat: 수업 문제 상세 조회 - 리더보드 / 제출
  src/App.tsx
  src/constants/paths.ts
  src/constants/queryKeys.ts
  src/pages/Class/ClassContestProblemList.tsx
  src/pages/Class/Problem/ContestProblemDetail.tsx
  src/pages/Class/Problem/ProblemLeaderBoard.tsx
  src/pages/Class/Problem/ProblemSubmission.tsx
  src/pages/Class/Problem/api/index.ts
  src/pages/Class/Problem/components/FileSubmissionForm.tsx
  src/pages/Class/Problem/components/LeaderboardSubmissionForm.tsx
  src/pages/Class/Problem/components/index.ts
  src/pages/Class/Problem/hooks/query/index.ts
  src/pages/Class/Problem/hooks/query/useContestProblemQuery.ts
  src/pages/Class/Problem/hooks/query/useContestProblemSubmissionQuery.ts
  src/pages/Class/Problem/hooks/query/useCreateContestProblemSubmissionCheckMutation.ts
  src/pages/Class/Problem/hooks/query/useCreateContestProblemSubmissionMutation.ts
  src/pages/Class/Problem/index.ts
  src/types/problem.d.ts
Labels: ✨feature

#61 feat: 관리자페이지 - FAQ 목록 조회, 생성, 삭제, 수정
  src/App.tsx
  src/constants/paths.ts
  src/constants/queryKeys.ts
  src/pages/Admin/AdminEditAnnouncement.tsx
  src/pages/Admin/AdminEditFaq.tsx
  src/pages/Admin/AdminFaqList.tsx
  src/pages/Admin/AdminNewAnnouncement.tsx
  src/pages/Admin/AdminNewFaq.tsx
  src/pages/Admin/api/index.ts
  src/pages/Admin/components/AdminCreateEditForm.tsx
  src/pages/Admin/hooks/index.ts
  src/pages/Admin/hooks/query/index.ts
  src/pages/Admin/hooks/query/useAdminFaqListQuery.ts
  src/pages/Admin/hooks/query/useAdminFaqQuery.ts
  src/pages/Admin/hooks/query/useCreateFaqMutation.ts
  src/pages/Admin/hooks/query/useDeleteFaqMutation.ts
  src/pages/Admin/hooks/query/useEditFaqMutation.ts
  src/pages/Admin/hooks/query/useEditFaqVisibleMutation.ts
  src/pages/Admin/hooks/useAdminFaqsTable.tsx
  src/pages/Admin/index.ts
  src/types/admin.d.ts
Labels: ✨feature

#62 feat: contest problem 생성 / 편집 / 삭제 / 기존 problem 편집
  src/App.tsx
  src/components/atom/index.ts
  src/constants/paths.ts
  src/pages/Class/ClassContestProblemList.tsx
  src/pages/Class/Problem/ProblemCreate.tsx
  src/pages/Class/Problem/ProblemEdit.tsx
  src/pages/Class/Problem/ProblemForm.tsx
  src/pages/Class/Problem/api/index.ts
  src/pages/Class/Problem/components/ProblemForm.tsx
  src/pages/Class/Problem/components/index.ts
  src/pages/Class/Problem/hooks/query/index.ts
  src/pages/Class/Problem/hooks/query/useCreateProblemMutation.ts
  src/pages/Class/Problem/hooks/query/useEditProblemMutation.ts
  src/pages/Class/Problem/index.ts
  src/pages/Class/components/ContestProblemCreateModal.tsx
  src/pages/Class/components/index.ts
  src/pages/Class/hooks/useClassProblemListTable.tsx
  src/pages/Class/hooks/useContestProblemListTable.tsx
Labels: ✨feature

#64 feat: 관리자페이지 - 사용자 관리
  src/App.tsx
  src/constants/paths.ts
  src/constants/queryKeys.ts
  src/pages/Admin/AdminUserList.tsx
  src/pages/Admin/api/index.ts
  src/pages/Admin/components/UserEditModal.tsx
  src/pages/Admin/hooks/index.ts
  src/pages/Admin/hooks/query/index.ts
  src/pages/Admin/hooks/query/useAdminUserListQuery.ts
  src/pages/Admin/hooks/query/useDeleteUserMutation.ts
  src/pages/Admin/hooks/query/useEditUserPrivilegeMutation.ts
  src/pages/Admin/hooks/query/useUserQuery.ts
  src/pages/Admin/hooks/useAdminUserTable.tsx
  src/pages/Admin/hooks/useModalBody.tsx
  src/pages/Admin/hooks/useSelectUserPrivilege.ts
  src/pages/Admin/index.ts
  src/types/admin.d.ts
Labels: ✨feature

#68 feat: 관리자페이지 페이지네이션 추가
  src/components/Pagination.tsx
  src/lib/pagination.ts
  src/pages/Admin/Announcement/AdminAnnouncementList.tsx
  src/pages/Admin/Announcement/api/index.ts
  src/pages/Admin/Announcement/hooks/query/useAdminAnnouncementListQuery.ts
  src/pages/Admin/Announcement/hooks/useAdminAnnouncementsTable.tsx
  src/pages/Admin/Class/AdminClassList.tsx
  src/pages/Admin/Class/api/index.ts
  src/pages/Admin/Class/hooks/query/useAdminClassListQuery.ts
  src/pages/Admin/Class/hooks/useAdminClassListTable.ts
  src/pages/Admin/Problem/AdminProblemList.tsx
  src/pages/Admin/Problem/api/index.ts
  src/pages/Admin/Problem/hooks/query/useAdminProblemListQuery.ts
  src/pages/Admin/Problem/hooks/useAdminProblemListTable.tsx
  src/pages/Admin/User/AdminUserList.tsx
  src/pages/Admin/User/api/index.ts
  src/pages/Admin/User/hooks/query/useAdminUserListQuery.ts
  src/pages/Admin/User/hooks/useAdminUserTable.tsx
  src/types/admin.d.ts
Labels: ✨feature

#70 feat: 관리자페이지 - 문제 상세
  src/App.tsx
  src/constants/paths.ts
  src/constants/queryKeys.ts
  src/pages/Admin/Problem/AdminProblemDetail.tsx
  src/pages/Admin/Problem/api/index.ts
  src/pages/Admin/Problem/hooks/query/index.ts
  src/pages/Admin/Problem/hooks/query/useProblemQuery.ts
  src/pages/Admin/Problem/hooks/useAdminProblemListTable.tsx
  src/pages/Admin/Problem/index.ts
Labels: ✨feature

#72 feat: 수업페이지 페이지네이션
  src/pages/Board/Board.tsx
  src/pages/Class/AllProblems/AllProblemList.tsx
  src/pages/Class/AllProblems/api/index.ts
  src/pages/Class/AllProblems/hooks/query/useAllProblemListQuery.ts
  src/pages/Class/AllProblems/hooks/useAllProblemListTable.tsx
  src/pages/Class/Contest/api/index.ts
  src/pages/Class/Contest/components/LeaderboardSubmissionForm.tsx
  src/pages/Class/Contest/hooks/query/useContestProblemSubmissionQuery.ts
  src/types/problem.d.ts
  src/types/response.d.ts
Labels: ✨feature

#73 feat: 건의게시판, 공지사항 페이지네이션
  src/pages/Announcement/Announcement.tsx
  src/pages/Announcement/api/index.ts
  src/pages/Announcement/hooks/query/useAnnouncementQuery.ts
  src/pages/Announcement/hooks/useAnnouncementTable.ts
  src/pages/Board/Board.tsx
  src/pages/Board/api/index.ts
  src/pages/Board/hooks/query/useProposalQuery.ts
  src/pages/Board/hooks/useProposalTable.ts
  src/types/announcement.d.ts
  src/types/proposal.d.ts
Labels: ✨feature
