Repository sos-sejong-opensource-software/seggle-frontend, pull requests merged in 2023-01, with the labels that each got.

#3 chore: webpack 리팩토링 및 dotEnv 설치
  .gitignore
  babel.config.js
  package-lock.json
  package.json
  webpack/loaders/asset.js
  webpack/loaders/index.js
  webpack/loaders/style.js
  webpack/loaders/typescript.js
  webpack/plugins/dotEnv.js
  webpack/plugins/htmlWebpack.js
  webpack/plugins/index.js
  webpack/plugins/tsConfigPaths.js
  webpack/server.js
  webpack/webpack.common.js
  webpack/webpack.dev.js
Labels: ♻️refactor

#6 feat: 로그인 페이지 구현
  package-lock.json
  package.json
  src/api/auth.ts
  src/api/index.ts
  src/api/interceptor.ts
  src/assets/fonts/Pretendard/webfont/woff2/Pretendard-Bold.woff2
  src/assets/fonts/Pretendard/webfont/woff2/Pretendard-ExtraBold.woff2
  src/assets/fonts/Pretendard/webfont/woff2/Pretendard-Medium.woff2
  src/assets/fonts/Pretendard/webfont/woff2/Pretendard-Regular.woff2
  src/assets/fonts/Pretendard/webfont/woff2/Pretendard-SemiBold.woff2
  src/components/atom/Button.tsx
  src/components/atom/ErrorMessage.tsx
  src/components/atom/Heading.tsx
  src/components/atom/index.ts
  src/constants/index.ts
  src/constants/localStorage.ts
  src/constants/paths.ts
  src/contexts/Auth.tsx
  src/contexts/index.ts
  src/index.tsx
  src/pages/Login/api/index.ts
  src/pages/Login/components/AuthForm.tsx
  src/pages/Login/components/index.ts
  src/pages/Login/constants/errorMessage.ts
  src/pages/Login/constants/index.ts
  src/pages/Login/hooks/index.ts
  src/pages/Login/hooks/useInput.ts
  src/pages/Login/hooks/useLogin.ts
  src/pages/Login/index.tsx
  src/style/index.css
  src/types/state.d.ts
  src/types/user.d.ts
  src/utils/decodeJwt.ts
  tailwind.config.cjs
Labels: ✨feature

#9 feat: 회원가입 페이지 구현
  src/pages/Login/components/AuthForm.tsx
  src/pages/Login/constants/errorMessage.ts
  src/pages/Login/constants/index.ts
  src/pages/Login/hooks/index.ts
  src/pages/Login/hooks/useInput.ts
  src/pages/Login/index.tsx
  src/pages/User/Login.tsx
  src/pages/User/Register.tsx
  src/pages/User/api/index.ts
  src/pages/User/components/AuthForm.tsx
  src/pages/User/components/index.ts
  src/pages/User/constants/errorMessage.ts
  src/pages/User/constants/index.ts
  src/pages/User/constants/input.ts
  src/pages/User/constants/regexp.ts
  src/pages/User/hooks/index.ts
  src/pages/User/hooks/useAuthForm.ts
  src/pages/User/hooks/useInput.ts
  src/pages/User/hooks/useLogin.ts
  src/pages/User/hooks/useRegister.ts
  src/pages/User/index.ts
  src/pages/index.ts
  src/types/user.d.ts
Labels: ✨feature

#11 feat: Select 컴포넌트 구현 및 Heading, Button, Modal 컴포넌트 수정
  src/components/Modal.tsx
  src/components/atom/Button.tsx
  src/components/atom/Heading.tsx
  src/components/atom/Select.tsx
  src/components/atom/index.ts
  src/components/index.ts
  src/components/molecule/Modal.tsx
  src/components/molecule/index.ts
  src/style/index.css
  tailwind.config.cjs
Labels: ✨feature, ♻️refactor

#16 feat: table component 구현
  src/components/molecule/Table.css
  src/components/molecule/Table.tsx
  src/components/molecule/index.ts
  src/pages/Home.tsx
Labels: ✨feature

#14 feat: FAQ 페이지 구현
  src/components/molecule/Accordion.tsx
  src/components/molecule/index.ts
  src/constants/index.ts
  src/constants/queryKeys.ts
  src/pages/Faq/Faq.tsx
  src/pages/Faq/api/index.ts
  src/pages/Faq/hooks/index.ts
  src/pages/Faq/hooks/query/index.ts
  src/pages/Faq/hooks/query/useFaqQuery.ts
  src/pages/Faq/hooks/useFaqAccordion.ts
  src/types/faq.d.ts
Labels: ✨feature

#12 feat: admin 사용자 정보 수정 모달 구현
  src/constants/index.ts
  src/constants/privilege.ts
  src/constants/queryKeys.ts
  src/pages/Admin/api/index.ts
  src/pages/Admin/components/UserEditModal.tsx
  src/pages/Admin/components/index.ts
  src/pages/Admin/hooks/index.ts
  src/pages/Admin/hooks/query/index.ts
  src/pages/Admin/hooks/query/useEditUserPrivilegeMutation.ts
  src/pages/Admin/hooks/query/useUserQuery.ts
  src/pages/Admin/hooks/useModalBody.tsx
  src/pages/Admin/hooks/useSelectUserPrivilege.ts
  src/types/user.d.ts
  src/utils/getPrivilegeNumber.ts
Labels: ✨feature

#19 feat: FAQ 페이지 비동기 처리 및 예외 처리
  src/App.tsx
  src/components/molecule/Accordion.tsx
  src/hooks/useSuspenseQuery.ts
  src/index.tsx
  src/pages/Faq/Faq.tsx
  src/pages/Faq/hooks/query/useFaqQuery.ts
  src/pages/Faq/hooks/useFaqAccordion.ts
Labels: ✨feature, ♻️refactor

#21 feat: 공지사항 리스트 조회
  src/App.tsx
  src/constants/queryKeys.ts
  src/pages/Announcement/Announcement.tsx
  src/pages/Announcement/api/index.ts
  src/pages/Announcement/hooks/index.ts
  src/pages/Announcement/hooks/query/index.ts
  src/pages/Announcement/hooks/query/useAnnouncementQuery.ts
  src/pages/Announcement/hooks/useAnnouncementTable.ts
  src/pages/Announcement/index.ts
  src/types/announcement.d.ts
  src/utils/time.tsx
Labels: ✨feature

#23 feat: 페이지 레이아웃 반응형 & Heading 반응형 수정
  src/App.tsx
  src/components/atom/Heading.tsx
  tailwind.config.cjs
Labels: ✨feature, ♻️refactor
